spring:
  datasource:
    druid:
      url: jdbc:mysql://122.51.203.80:3306/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: as123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.gokibe.myshop.entity
  mapper-locations: classpath:mapper/*.xml